-- if spaces keep status as it was
-- ------------------------------
-- if SIG INT status = 1       DONE
-- ------------------------------
-- expand herdoc << ""         DONE
-- ------------------------------
-- multi herdocs               DONE
-- ------------------------------
-- files are still there in herdoc  DONE
-- ------------------------------
-- cat | cat | cat       SIGNAL
-- ------------------------------
-- use multi lss and cats    MULTI FORK
-- ------------------------------
-- multi ps                  DONE
-- ------------------------------
-- bash-3.2$ cat "?"
-- bash-3.2$ (( hostname && lss) > "?")       DONE
-- ---------------------
-- export | export ""        DONE
-- -------------------
-- top                       DONE
-- -------------------
-- minishell$> mkdir -p 1/2/3            CD && PWD
-- minishell$> cd 1/2/3/
-- minishell$> chmod 0 .
-- minishell$> cd ..
-- minishell: cd: ..: Permission denied
-- ----------------------
-- unset PWD OLDPWD should not cree in cd        DONE
-- ------------------------
-- $a | $b && cat            DONE
-- ------------------------
-- elkess@e3r7p18 minishell % env -i ./minishell       DONE
-- minishell$> export
-- declare -x OLDPWD="OLDPWD"
-- declare -x PATH="/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:."
-- declare -x PWD="/mnt/homes/melkess/Desktop/_minishell/minishell"
-- declare -x SHLVL="1"
-- minishell$> unset OLDPWD
-- minishell$> export   
-- ------------------------
-- melkess@e3r7p18 minishell % env -i ./minishell        DONE
-- minishell$> unset OLDPWD
-- minishell$> unset OLDPWD
-- --------------------------

-- 1) cd 
-- minishell$> ../../minishell   DONE
-- └── Command Node: 0
--       Cmd: ../../minishell 
--       Redirs: (none)
--     // Root
-- ERROR           
-- --------------------------
-- when dir is deleted

-- 2)
-- ➜  minishell git:(main) ✗ (ulimit -u 20 && ./minishell )  DONE
-- minishell$> pwd
-- └── Command Node: 0
--       Cmd: pwd 
--       Redirs: (none)
--     // Root
-- /mnt/homes/sgmih/Desktop/laaast /_minishell/minishell
-- minishell$> ls
-- └── Command Node: 0
--       Cmd: ls 
--       Redirs: (none)
--     // Root
-- 	Fork1 Failed: Resource temporarily unavailabl
-- --------------------------
-- if PATH="" put .            DONEE
-- --------------------------
-- () -> subshell
-- -------------------
-- pwd | cd  (../../minishell when dir is deleted) segfault      CD && PWD
-- -------------------

-- cat | cat | cat | ls  => leaks

-- << '' => leak

-- unset USER -> unset MallocNanoZone => leaks

-- [
--     ➜  minishell$ unset PWD OLDPWD
--     ➜  minishell$ echo $PWD

--     ➜  minishell$ cd ,,.
--     minishell: cd: ,,. No such file or directory
--     ➜  minishell$ cd ..
--     [1]    21459 segmentation fault  ./minishell
-- ]    
